# Generated by Django 2.2.4 on 2019-11-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.FileField(upload_to='images/'),
        ),
    ]
