# Generated by Django 2.2.4 on 2019-11-27 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191127_0534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['cover']},
        ),
    ]
