# Generated by Django 2.2.4 on 2019-11-27 11:34

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191127_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.FileField(upload_to='files/%Y/%m/%d', validators=[app.validators.validate_file_extension]),
        ),
    ]
